version: "3.8"

networks:
  analytics:
    name: analytics

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_analytics
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
    networks:
      - analytics

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_analytics
    volumes:
      - ./:/var/www/html
    networks:
      - analytics

  mysql:
    image: mysql:5.7.32
    container_name: mysql_analytics
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - analytics
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    
  composer:
    image: composer:latest
    container_name: composer_analytics
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - analytics
    
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan_analytics
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', 'artisan']
    networks:
      - analytics

  npm:
    image: node:current-alpine
    container_name: npm_analytics
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - analytics

  npx:
    image: node:current-alpine
    container_name: npx_analytics
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npx']
    networks:
      - analytics
