version: "3.8"

networks:
  book-review:
    name: book-review

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_book-review
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
    networks:
      - book-review

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_book-review
    volumes:
      - ./:/var/www/html
    networks:
      - book-review

  mysql:
    image: mysql:5.7.32
    container_name: mysql_book-review
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - book-review
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    
  composer:
    image: composer:latest
    container_name: composer_book-review
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - book-review
    
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan_book-review
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', 'artisan']
    networks:
      - book-review

  npm:
    image: node:current-alpine
    container_name: npm_book-review
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - book-review

  npx:
    image: node:current-alpine
    container_name: npx_book-review
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npx']
    networks:
      - book-review
